alu: alu.sv
	iverilog alu.sv -o alu
regfile:regfile.sv
	iverilog regfile.sv -o regfile
insmem:insmem.sv
	iverilog insmem.sv -o insmem
signextended:signextended.sv
	iverilog signextended.sv -o signextended
clean:
	rm -f alu regfile insmem signextended
